export const charactersWithDetails = [
  {
    _id: 1,
    tvShows: ["Hercules (TV series)"],
    videoGames: ["Kingdom Hearts III"],
    imageUrl:
      'src="https://static.wikia.nocookie.net/disney/images/d/d3/Vlcsnap-2015-05-06-23h04m15s601.png"',
  },
];

export const characterItems = [
  {
    _id: 112,
    name: "Achilles",
    tvShows: ["Hercules (TV series)"],
    videoGames: ["Kingdom Hearts III"],
    films: ["Hercules (film)"],
    allies: [],
    enemies: [],
    __typename: "Character",
  },
  {
    _id: 18,
    name: "Abigail the Cow",
    tvShows: [],
    videoGames: [],
    films: ["The Fox and the Hound", "The Fox and the Hound 2"],
    allies: [],
    enemies: [],
    __typename: "Character",
  },
  {
    _id: 16,
    name: "Abdullah",
    tvShows: [],
    videoGames: [],
    films: ["Cheetah"],
    allies: [],
    enemies: [],
    __typename: "Character",
  },
  {
    _id: 45,
    name: "Admiral Boom and Mr. Binnacle",
    tvShows: [],
    videoGames: [],
    films: ["Mary Poppins (film)", "Mary Poppins Returns"],
    allies: [],
    enemies: [],
    __typename: "Character",
  },
  {
    _id: 7,
    name: ".GIFfany",
    tvShows: ["Gravity Falls"],
    videoGames: [],
    films: [],
    allies: [],
    enemies: [],
    __typename: "Character",
  },
  {
    _id: 12,
    name: "90's Adventure Bear",
    tvShows: ["Pickle and Peanut"],
    videoGames: [],
    films: [],
    allies: [],
    enemies: [],
    __typename: "Character",
  },
  {
    _id: 36,
    name: "Candace Adams",
    tvShows: ["K.C. Undercover"],
    videoGames: [],
    films: [],
    allies: [],
    enemies: [],
    __typename: "Character",
  },
  {
    _id: 139,
    name: "Ahadi",
    tvShows: [],
    videoGames: [],
    films: ["The Lion King", "The Lion King (2019 film)"],
    allies: [],
    enemies: [],
    __typename: "Character",
  },
  {
    _id: 152,
    name: "Al Muddy Sultan",
    tvShows: ["Aladdin (TV series)"],
    videoGames: [],
    films: [],
    allies: [],
    enemies: [],
    __typename: "Character",
  },
  {
    _id: 181,
    name: "Irwina Allen",
    tvShows: ["Chip 'n Dale Rescue Rangers"],
    videoGames: [],
    films: [],
    allies: [],
    enemies: [],
    __typename: "Character",
  },
];

export const pieChartDataPoints = [
  {
    name: "Mikey",
    y: 2,
    films: ["Terminator", "Back to the future"],
  },
  {
    name: "Donald",
    y: 4,
    films: ["Blade runner", "film2", "film3", "film4"],
  },
  {
    name: "Taz",
    y: 7,
    films: ["film5", "film6", "film7", "film8", "film9", "film10", "film11"],
  },
  { name: "char1", y: 0, films: [] },
];
